=== joanayala684-wq/HTML_CSS/XSD/ejemplos alumnos/Ejemplo1nota.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="nota">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="para" type="xs:string" />
                <xs:element name="de" type="xs:string" />
                <xs:element name="numero" type="xs:integer" />
                <xs:element name="cabecera" type="xs:string" />
                <xs:element name="mensaje" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="fecha" type="xs:date" />
                <xs:element name="hora" type="xs:time" />
                <xs:element name="leido" type="xs:boolean" />
            </xs:sequence>
        </xs:complexType> 
    </xs:element>
</xs:schema>

=== joanayala684-wq/HTML_CSS/XSD/ejemplos alumnos/Ejemplo1nota.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<nota xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="Ejemplo1nota.xsd" >
    <para>Marta</para>
    <de>Jose</de>
    <numero>27</numero>    
    <cabecera>Recordatorio</cabecera>
    <mensaje>No te olvides de echar la primitiva</mensaje>
    <fecha>2026-02-28</fecha>
    <hora>12:10:05</hora>
    <leido>true</leido>
</nota>
