<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE marcadores [
<!ELEMENT marcadores (pagina+)>
<!ELEMENT pagina (nombre, descripcion, url)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT url (#PCDATA)>
]>
<marcadores>
    <pagina>
        <nombre>Buscador</nombre>
        <descripcion>Buscador de información</descripcion>
        <url>http://www.google.es</url>
    </pagina>
    <pagina>
        <nombre>Wikipedia</nombre>
        <descripcion>La enciclopedia libre</descripcion>
        <url>http://www.wikipedia.org/</url>
    </pagina>
    <pagina>
        <nombre>W3C</nombre>
        <descripcion>World Wide Web Consortium</descripcion>
        <url>http://www.w3.org/</url>
    </pagina>
</marcadores>