=== joanayala684-wq/HTML_CSS/DTD/Ejemplos DTD/ejemplos3/ej1.dtd
<!ELEMENT matricula (personal,pago)>
<!ELEMENT personal (dni,nombre,titulacion,curso_academico,domicilios)>
<!ELEMENT dni (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT titulacion (#PCDATA)>
<!ELEMENT curso_academico (#PCDATA)>

<!ELEMENT domicilios (domicilio+)>
<!ELEMENT domicilio (nombre)  >
<!ATTLIST domicilio tipo (familiar | habitual) #REQUIRED>
<!ELEMENT pago (tipo_matricula)>
<!ELEMENT tipo_matricula (#PCDATA)>

=== joanayala684-wq/HTML_CSS/DTD/Ejemplos DTD/ejemplos3/ej1.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE matricula SYSTEM "ej1.dtd">
<matricula>
    <personal>
        <dni>99223366M</dni>
        <nombre>Juan Pardo Martín</nombre>
        <titulacion>Ingeniería Informática</titulacion>
        <curso_academico>2023/2024</curso_academico>
        <domicilios>
            <domicilio tipo="familiar">
                <nombre>C/ Principal nº1</nombre>
            </domicilio>
            <domicilio tipo="habitual">
                <nombre>C/ Secundaria nº2</nombre>
            </domicilio>
        </domicilios>
    </personal>
    <pago>
        <tipo_matricula>Matrícula Ordinaria</tipo_matricula>
    </pago>
</matricula>
